/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tagidentification_ResultsActivity */

#ifndef _Included_com_example_tagidentification_ResultsActivity
#define _Included_com_example_tagidentification_ResultsActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tagidentification_ResultsActivity
 * Method:    processFileNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_tagidentification_ResultsActivity_processFileNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
